extension CheckRetValueOpenJellycoreTests {
    var retval_OpenJellycoreTests_testIssue31Interpolation: String {
        return """
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>WFWorkflowActions</key>
	<array>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.gettext</string>
			<key>WFWorkflowActionParameters</key>
			<dict>
				<key>CustomOutputName</key>
				<string>Generated Magic Variable 9E3C1AC8-4B54-4DBB-8D1F-0E3E7DB20F15</string>
				<key>UUID</key>
				<string>9E3C1AC8-4B54-4DBB-8D1F-0E3E7DB20F15</string>
				<key>WFTextActionText</key>
				<string>Pp</string>
			</dict>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.setvariable</string>
			<key>WFWorkflowActionParameters</key>
			<dict>
				<key>WFInput</key>
				<dict>
					<key>Value</key>
					<dict>
						<key>Aggrandizements</key>
						<array/>
						<key>OutputName</key>
						<string>Generated Magic Variable 9E3C1AC8-4B54-4DBB-8D1F-0E3E7DB20F15</string>
						<key>OutputUUID</key>
						<string>9E3C1AC8-4B54-4DBB-8D1F-0E3E7DB20F15</string>
						<key>Type</key>
						<string>ActionOutput</string>
					</dict>
					<key>WFSerializationType</key>
					<string>WFTextTokenAttachment</string>
				</dict>
				<key>WFVariableName</key>
				<string>varA</string>
			</dict>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.dictionary</string>
			<key>WFWorkflowActionParameters</key>
			<dict>
				<key>CustomOutputName</key>
				<string>dict0</string>
				<key>UUID</key>
				<string>656093D5-55B2-4CFB-A479-816D05C7A3EE</string>
			</dict>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.setvalueforkey</string>
			<key>WFWorkflowActionParameters</key>
			<dict>
				<key>CustomOutputName</key>
				<string>dict</string>
				<key>UUID</key>
				<string>AF293F33-01F7-4591-B2BE-E7726DA8777F</string>
				<key>WFDictionary</key>
				<dict>
					<key>Value</key>
					<dict>
						<key>Aggrandizements</key>
						<array/>
						<key>OutputName</key>
						<string>dict0</string>
						<key>OutputUUID</key>
						<string>656093D5-55B2-4CFB-A479-816D05C7A3EE</string>
						<key>Type</key>
						<string>ActionOutput</string>
					</dict>
					<key>WFSerializationType</key>
					<string>WFTextTokenAttachment</string>
				</dict>
				<key>WFDictionaryKey</key>
				<string>A</string>
				<key>WFDictionaryValue</key>
				<string>QqQ</string>
			</dict>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.getvalueforkey</string>
			<key>WFWorkflowActionParameters</key>
			<dict>
				<key>CustomOutputName</key>
				<string>magicA</string>
				<key>UUID</key>
				<string>1422FD92-2463-40AD-BD1C-15575A86A437</string>
				<key>WFDictionaryKey</key>
				<string>A</string>
				<key>WFInput</key>
				<dict>
					<key>Value</key>
					<dict>
						<key>Aggrandizements</key>
						<array/>
						<key>OutputName</key>
						<string>dict</string>
						<key>OutputUUID</key>
						<string>AF293F33-01F7-4591-B2BE-E7726DA8777F</string>
						<key>Type</key>
						<string>ActionOutput</string>
					</dict>
					<key>WFSerializationType</key>
					<string>WFTextTokenAttachment</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.gettext</string>
			<key>WFWorkflowActionParameters</key>
			<dict>
				<key>CustomOutputName</key>
				<string>Generated Magic Variable AF1CC34C-C7FE-4B5C-B550-A009D61D201B</string>
				<key>UUID</key>
				<string>AF1CC34C-C7FE-4B5C-B550-A009D61D201B</string>
				<key>WFTextActionText</key>
				<dict>
					<key>Value</key>
					<dict>
						<key>attachmentsByRange</key>
						<dict>
							<key>{3, 1}</key>
							<dict>
								<key>Aggrandizements</key>
								<array/>
								<key>Type</key>
								<string>Variable</string>
								<key>VariableName</key>
								<string>varA</string>
							</dict>
							<key>{6, 1}</key>
							<dict>
								<key>Aggrandizements</key>
								<array/>
								<key>OutputName</key>
								<string>magicA</string>
								<key>OutputUUID</key>
								<string>1422FD92-2463-40AD-BD1C-15575A86A437</string>
								<key>Type</key>
								<string>ActionOutput</string>
							</dict>
						</dict>
						<key>string</key>
						<string>xxx￼yy￼z</string>
					</dict>
					<key>WFSerializationType</key>
					<string>WFTextTokenString</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.setvariable</string>
			<key>WFWorkflowActionParameters</key>
			<dict>
				<key>WFInput</key>
				<dict>
					<key>Value</key>
					<dict>
						<key>Aggrandizements</key>
						<array/>
						<key>OutputName</key>
						<string>Generated Magic Variable AF1CC34C-C7FE-4B5C-B550-A009D61D201B</string>
						<key>OutputUUID</key>
						<string>AF1CC34C-C7FE-4B5C-B550-A009D61D201B</string>
						<key>Type</key>
						<string>ActionOutput</string>
					</dict>
					<key>WFSerializationType</key>
					<string>WFTextTokenAttachment</string>
				</dict>
				<key>WFVariableName</key>
				<string>varB</string>
			</dict>
		</dict>
	</array>
	<key>WFWorkflowClientRelease</key>
	<real>3</real>
	<key>WFWorkflowClientVersion</key>
	<string>1050.24</string>
	<key>WFWorkflowIcon</key>
	<dict>
		<key>WFWorkflowIconGlyphNumber</key>
		<integer>61440</integer>
		<key>WFWorkflowIconStartColor</key>
		<integer>4282601983</integer>
	</dict>
	<key>WFWorkflowImportQuestions</key>
	<array/>
	<key>WFWorkflowInputContentItemClasses</key>
	<array/>
	<key>WFWorkflowMinimumClientVersion</key>
	<integer>900</integer>
	<key>WFWorkflowMinimumClientVersionString</key>
	<string>900</string>
	<key>WFWorkflowTypes</key>
	<array>
		<string>NCWidget</string>
	</array>
</dict>
</plist>

"""
    }
}
