extension CheckRetValueOpenJellycoreTests {
    var retval_OpenJellycoreTests_testIssue31Interpolation: String {
        return """
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>WFWorkflowActions</key>
	<array>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.gettext</string>
			<key>WFWorkflowActionParameters</key>
			<dict>
				<key>CustomOutputName</key>
				<string>Generated Magic Variable 05860D6A-649B-4068-A0E9-E3EC3A2B10CC</string>
				<key>UUID</key>
				<string>05860D6A-649B-4068-A0E9-E3EC3A2B10CC</string>
				<key>WFTextActionText</key>
				<string>b</string>
			</dict>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.setvariable</string>
			<key>WFWorkflowActionParameters</key>
			<dict>
				<key>WFInput</key>
				<dict>
					<key>Value</key>
					<dict>
						<key>Aggrandizements</key>
						<array/>
						<key>OutputName</key>
						<string>Generated Magic Variable 05860D6A-649B-4068-A0E9-E3EC3A2B10CC</string>
						<key>OutputUUID</key>
						<string>05860D6A-649B-4068-A0E9-E3EC3A2B10CC</string>
						<key>Type</key>
						<string>ActionOutput</string>
					</dict>
					<key>WFSerializationType</key>
					<string>WFTextTokenAttachment</string>
				</dict>
				<key>WFVariableName</key>
				<string>varA</string>
			</dict>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.dictionary</string>
			<key>WFWorkflowActionParameters</key>
			<dict>
				<key>CustomOutputName</key>
				<string>dict0</string>
				<key>UUID</key>
				<string>A408D42B-4832-418B-9C82-005418358CAC</string>
			</dict>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.setvalueforkey</string>
			<key>WFWorkflowActionParameters</key>
			<dict>
				<key>CustomOutputName</key>
				<string>dict</string>
				<key>UUID</key>
				<string>A8465A1E-5605-4F03-98BF-D812C0B6D590</string>
				<key>WFDictionary</key>
				<dict>
					<key>Value</key>
					<dict>
						<key>Aggrandizements</key>
						<array/>
						<key>OutputName</key>
						<string>dict0</string>
						<key>OutputUUID</key>
						<string>A408D42B-4832-418B-9C82-005418358CAC</string>
						<key>Type</key>
						<string>ActionOutput</string>
					</dict>
					<key>WFSerializationType</key>
					<string>WFTextTokenAttachment</string>
				</dict>
				<key>WFDictionaryKey</key>
				<string>A</string>
				<key>WFDictionaryValue</key>
				<string>Q</string>
			</dict>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.getvalueforkey</string>
			<key>WFWorkflowActionParameters</key>
			<dict>
				<key>CustomOutputName</key>
				<string>magicA</string>
				<key>UUID</key>
				<string>EBF6DD1E-9FE0-4F20-9B73-39D7BF1E90DC</string>
				<key>WFDictionaryKey</key>
				<string>A</string>
				<key>WFInput</key>
				<dict>
					<key>Value</key>
					<dict>
						<key>Aggrandizements</key>
						<array/>
						<key>OutputName</key>
						<string>dict</string>
						<key>OutputUUID</key>
						<string>A8465A1E-5605-4F03-98BF-D812C0B6D590</string>
						<key>Type</key>
						<string>ActionOutput</string>
					</dict>
					<key>WFSerializationType</key>
					<string>WFTextTokenAttachment</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.gettext</string>
			<key>WFWorkflowActionParameters</key>
			<dict>
				<key>CustomOutputName</key>
				<string>Generated Magic Variable 5B09B4C9-1AF2-4E6F-BEF7-ED4BACBC6156</string>
				<key>UUID</key>
				<string>5B09B4C9-1AF2-4E6F-BEF7-ED4BACBC6156</string>
				<key>WFTextActionText</key>
				<dict>
					<key>Value</key>
					<dict>
						<key>attachmentsByRange</key>
						<dict>
							<key>{1, 1}</key>
							<dict>
								<key>Aggrandizements</key>
								<array/>
								<key>Type</key>
								<string>Variable</string>
								<key>VariableName</key>
								<string>varA</string>
							</dict>
							<key>{3, 1}</key>
							<dict>
								<key>Aggrandizements</key>
								<array/>
								<key>OutputName</key>
								<string>magicA</string>
								<key>OutputUUID</key>
								<string>EBF6DD1E-9FE0-4F20-9B73-39D7BF1E90DC</string>
								<key>Type</key>
								<string>ActionOutput</string>
							</dict>
						</dict>
						<key>string</key>
						<string>x￼y￼z</string>
					</dict>
					<key>WFSerializationType</key>
					<string>WFTextTokenString</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.setvariable</string>
			<key>WFWorkflowActionParameters</key>
			<dict>
				<key>WFInput</key>
				<dict>
					<key>Value</key>
					<dict>
						<key>Aggrandizements</key>
						<array/>
						<key>OutputName</key>
						<string>Generated Magic Variable 5B09B4C9-1AF2-4E6F-BEF7-ED4BACBC6156</string>
						<key>OutputUUID</key>
						<string>5B09B4C9-1AF2-4E6F-BEF7-ED4BACBC6156</string>
						<key>Type</key>
						<string>ActionOutput</string>
					</dict>
					<key>WFSerializationType</key>
					<string>WFTextTokenAttachment</string>
				</dict>
				<key>WFVariableName</key>
				<string>varB</string>
			</dict>
		</dict>
	</array>
	<key>WFWorkflowClientRelease</key>
	<real>3</real>
	<key>WFWorkflowClientVersion</key>
	<string>1050.24</string>
	<key>WFWorkflowIcon</key>
	<dict>
		<key>WFWorkflowIconGlyphNumber</key>
		<integer>61440</integer>
		<key>WFWorkflowIconStartColor</key>
		<integer>4282601983</integer>
	</dict>
	<key>WFWorkflowImportQuestions</key>
	<array/>
	<key>WFWorkflowInputContentItemClasses</key>
	<array/>
	<key>WFWorkflowMinimumClientVersion</key>
	<integer>900</integer>
	<key>WFWorkflowMinimumClientVersionString</key>
	<string>900</string>
	<key>WFWorkflowTypes</key>
	<array>
		<string>NCWidget</string>
	</array>
</dict>
</plist>

"""
    }
}
